[common]
#log-local-time = true
log-dir = "logs"
#log-level = "INFO"
log-level = "{$LOG_LEVEL}"
log-buffer-size = 0
log-buffer-delay = 0

mem-stats-period = 1800
mem-stats-level = "INFO"

#----------------------------------------------------------------------------------------------------------------------------#

[http]
listener = { bind-addr = ":{$PORT}", ssl-combined-pem = "", timeout = 5 }

#----------------------------------------------------------------------------------------------------------------------------#

[others]
option1 = "Hello"
option2 = "world!"

#----------------------------------------------------------------------------------------------------------------------------#
