[common]
name = "Service template"
description = "Service template example"

#log-local-time = true
log-dir = "logs"
#log-level = "INFO"
log-level = "{$LOG_LEVEL}"
log-buffer-size = 0
log-buffer-delay = 0

mem-stats-period = 1800
mem-stats-level = "INFO"

load-avg-period = 60

profiler-enabled = false 
deep-profiling = false

#----------------------------------------------------------------------------------------------------------------------------#

[http]
listener = { bind-addr = ":{$PORT}", ssl-combined-pem = "", timeout = 5 }

#----------------------------------------------------------------------------------------------------------------------------#

[others]
{#include include-example.toml}

#----------------------------------------------------------------------------------------------------------------------------#
