[common]
name = "Service template"
description = "Service example"
class = ""

#log-local-time = true
log-dir = "logs"
#log-level = "INFO"
log-level = "{$LOG_LEVEL}"
log-buffer-size = 0
log-buffer-delay = 0

#go-max-procs = 4

mem-stats-period = 1800
mem-stats-level = "INFO"

load-avg-period = 60

profiler-enabled = false 
deep-profiling = false

disabled-endpoints = []

#----------------------------------------------------------------------------------------------------------------------------#

[http]
listener = { bind-addr = ":{$PORT}", ssl-combined-pem = "", timeout = 5, icon-file = "favicon.ico", basic-auth-enabled = false, users = {{#include users.toml}} }

#----------------------------------------------------------------------------------------------------------------------------#

[others]
{#include include-example.toml}

#----------------------------------------------------------------------------------------------------------------------------#
