#----------------------------------------------------------------------------------------------------------------------------#

# Общие стандартные параметры

[common]
# Название приложения
name = "Service template"

# Описание приложения
description = "Service example"

# Класс приложения
class = "service-template"

{#include ^/common.toml}

#----------------------------------------------------------------------------------------------------------------------------#

# Параметры http интерфейса

[http]
# Листенер
listener = { \
	# Адрес, на котором слушать
	bind-addr = ":{$PORT}", \

	# Префикс, который может добавляться прокси для идентификации приложения
	proxy-prefix = "/service-template/", \

	{#include ^/http.toml} \
}

#----------------------------------------------------------------------------------------------------------------------------#

# Дополнительные параметры

[others]
{#include ^/include-example.toml}

#----------------------------------------------------------------------------------------------------------------------------#
