[common]
name = "Service template"
description = "Service example"
class = ""

#log-local-time = true
log-dir = "logs"
log-level = "{$LOG_LEVEL}"
log-levels = {}
log-buffer-size = 0
log-buffer-delay = 0
log-max-string-len = 10000

#go-max-procs = 4

mem-stats-period = 1800
mem-stats-level = "INFO"

load-avg-period = 60

profiler-enabled = false 
deep-profiling = false

use-std-json = false

min-size-for-gzip = 256

#----------------------------------------------------------------------------------------------------------------------------#

[http]
listener = { \
             bind-addr = ":{$PORT}", ssl-combined-pem = "", timeout = 5, \
             root = "", \
             icon-file = "html/favicon.ico", \
             disabled-endpoints = [], \
             basic-auth-enabled = false, \
             jwt-secret = "", \
             jwt-lifetime = 157680000, \
             jwt-endpoints = [], \
             users = {{#include ^users.toml}} \
           }

#----------------------------------------------------------------------------------------------------------------------------#

[others]
{#include ^include-example.toml}

#----------------------------------------------------------------------------------------------------------------------------#
